polling_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:poll_id>/', views.detail, name='detail'),
    path('<int:poll_id>/results/', views.results, name='results'),
    path('<int:poll_id>/vote/', views.vote, name='vote'),
    path('create/', views.create_poll, name='create'),
    path('<int:poll_id>/add_choice/', views.add_choice, name='add_choice'),
]

polls/models.py
# from django.db import models
from djongo import models

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    # votes = models.IntegerField(default=0)
    votes = models.IntegerField(default=0)

polls/forms.py
from django import forms
from .models import Poll, Choice

class PollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ['question']


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']

polls/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Choice, Poll
from .forms import PollForm, ChoiceForm

def index(request):
    latest_poll_list = Poll.objects.order_by('-pub_date')
    context = {'latest_poll_list': latest_poll_list}
    return render(request, 'polls/index.html', context)

def detail(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/detail.html', {'poll': poll})

def results(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/results.html', {'poll': poll})

def vote(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = poll.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'poll': poll,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(poll.id,)))



def create_poll(request):
    if request.method == 'POST':
        form = PollForm(request.POST)
        if form.is_valid():
            poll = form.save()
            # return redirect('polls:index')  # Redirect to poll list
            return redirect('polls:detail', poll_id=poll.id)  # Redirect to poll detail
    else:
        form = PollForm()
    return render(request, 'polls/create_poll.html', {'form': form})


def add_choice(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    if request.method == 'POST':
        form = ChoiceForm(request.POST)
        if form.is_valid():
            choice = form.save(commit=False)
            choice.poll = poll
            choice.save()
            return redirect('polls:detail', poll_id=poll.id)  # Redirect to poll detail
    else:
        form = ChoiceForm()
    return render(request, 'polls/add_choice.html', {'form': form, 'poll': poll})

polls/templates/polls/add_choice.html
<!DOCTYPE html>
<html>
<head>
    <title>Add Choice to Poll</title>
</head>
<body>
    <h1>Add Choice to Poll: {{ poll.question }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Choice</button>
    </form>
    <a href="{% url 'polls:detail' poll.id %}">Back to Poll</a>
</body>
</html>

polls/templates/polls/create_poll.html
<!DOCTYPE html>
<html>
<head>
    <title>Create Poll</title>
</head>
<body>
    <h1>Create a New Poll</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Poll</button>
    </form>
</body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
  <head>
    <title>{{ poll.question }}</title>
  </head>
  <body>
    <h1>{{ poll.question }}</h1>
    <form action="{% url 'polls:vote' poll.id %}" method="post">
      {% csrf_token %} {% for choice in poll.choice_set.all %}
      <input
        type="radio"
        name="choice"
        id="choice{{ forloop.counter }}"
        value="{{ choice.id }}"
      />
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
      ><br />
      {% endfor %}
      <input type="submit" value="Vote" />
    </form>
    <a href="{% url 'polls:add_choice' poll.id %}">Add Choice</a>
  </body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Polling System</title>
</head>
<body>
    <h1>Polls</h1>
    <ul>
    {% for poll in latest_poll_list %}
        <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
    <a href="{% url 'polls:create' %}">Create a Poll</a>
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html>
  <head>
    <title>Results for {{ poll.question }}</title>
  </head>
  <body>
    <h1>Results for {{ poll.question }}</h1>
    <ul>
      {% for choice in poll.choice_set.all %}
      <li>{{ choice.choice_text }} - Votes: {{ choice.votes }}</li>
      {% endfor %}
    </ul>
    <a href="{% url 'polls:index' %}">Back to Polls</a>
  </body>
</html>